### ISSUE TITLE
Windows - Drop file

### ISSUE THREAD

**Issue by bwyyoung** [qweasd1/hyper-drop-file#3]
It doesnt seem to work correctly on Windows.
The directory is dropped as windows formatted directory, but not UNIX style (/c/Users/briany1/Documents/AndroidStudioProjects/paint)

![Screenshot_040820_062525_PM](https://user-images.githubusercontent.com/1365439/78773798-5254dc00-79c6-11ea-8643-e7e4e8065ca5.jpg)

**Comment by qweasd1** [comment]
I think the easiest way is you can directly folk this project and make some modification. Currently, the plugin will use the default path format for the platform, so if it's windows, then it will use windows format. You can go to line 45 of index.js file and modify the file.path to linux style and install it to your hyper terminal, I think this will solve your issue. Maybe in the future, I will detect the current shell to decide which path format to use instead of platform, but don't time to explore this at this moment, sorry for that!
